(function(){var h={},mt={},c={id:"f628d86243daf05c564aa17f55e27b02",dm:["jser.me"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:0,vcard:0,qiao:0,lxb:0,conv:0,comm:0,apps:''};var q=!0,r=null,s=!1;mt.j={};mt.j.V=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.j.cookieEnabled=navigator.cookieEnabled;mt.j.javaEnabled=navigator.javaEnabled();mt.j.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.j.Ka=(window.screen.width||0)+"x"+(window.screen.height||0);mt.j.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,d,f){var b;f.J&&(b=new Date,b.setTime(b.getTime()+f.J));document.cookie=a+"="+d+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(b?"; expires="+b.toGMTString():"")+(f.Za?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:r};mt.r={};mt.r.Ta=function(a){return document.getElementById(a)};mt.r.pa=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return r};
(mt.r.Ia=function(){function a(){if(!a.C){a.C=q;for(var e=0,d=b.length;e<d;e++)b[e]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var f=s,b=[],e;document.addEventListener?e=function(){document.removeEventListener("DOMContentLoaded",e,s);a()}:document.attachEvent&&(e=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",e),a())});(function(){if(!f)if(f=q,"complete"===document.readyState)a.C=q;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
e,s),window.addEventListener("load",a,s);else if(document.attachEvent){document.attachEvent("onreadystatechange",e);window.attachEvent("onload",a);var b=s;try{b=window.frameElement==r}catch(p){}document.documentElement.doScroll&&b&&d()}})();return function(e){a.C?e():b.push(e)}}()).C=s;mt.event={};mt.event.c=function(a,d,f){a.attachEvent?a.attachEvent("on"+d,function(b){f.call(a,b)}):a.addEventListener&&a.addEventListener(d,f,s)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=s};mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=f[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function d(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(b){switch(typeof b){case "undefined":return"undefined";case "number":return isFinite(b)?String(b):"null";case "string":return a(b);case "boolean":return String(b);
default:if(b===r)return"null";if(b instanceof Array){var e=["["],f=b.length,p,g,k;for(g=0;g<f;g++)switch(k=b[g],typeof k){case "undefined":case "function":case "unknown":break;default:p&&e.push(","),e.push(mt.m.stringify(k)),p=1}e.push("]");return e.join("")}if(b instanceof Date)return'"'+b.getFullYear()+"-"+d(b.getMonth()+1)+"-"+d(b.getDate())+"T"+d(b.getHours())+":"+d(b.getMinutes())+":"+d(b.getSeconds())+'"';p=["{"];g=mt.m.stringify;for(f in b)if(Object.prototype.hasOwnProperty.call(b,f))switch(k=
b[f],typeof k){case "undefined":case "unknown":case "function":break;default:e&&p.push(","),e=1,p.push(g(f)+":"+g(k))}p.push("}");return p.join("")}}}();mt.lang={};mt.lang.e=function(a,d){return"[object "+d+"]"==={}.toString.call(a)};mt.lang.Wa=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.Ya=function(a){return mt.lang.e(a,"String")};mt.localStorage={};
mt.localStorage.H=function(){if(!mt.localStorage.g)try{mt.localStorage.g=document.createElement("input"),mt.localStorage.g.type="hidden",mt.localStorage.g.style.display="none",mt.localStorage.g.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.g)}catch(a){return s}return q};
mt.localStorage.set=function(a,d,f){var b=new Date;b.setTime(b.getTime()+f||31536E6);try{window.localStorage?(d=b.getTime()+"|"+d,window.localStorage.setItem(a,d)):mt.localStorage.H()&&(mt.localStorage.g.expires=b.toUTCString(),mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.setAttribute(a,d),mt.localStorage.g.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var d=a.indexOf("|"),f=a.substring(0,d)-0;if(f&&f>(new Date).getTime())return a.substring(d+1)}}else if(mt.localStorage.H())try{return mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.getAttribute(a)}catch(b){}return r};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.H())try{mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.removeAttribute(a),mt.localStorage.g.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,d){if(window.sessionStorage)try{window.sessionStorage.setItem(a,d)}catch(f){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):r};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.Q={};mt.Q.log=function(a,d){var f=new Image,b="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[b]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=r;f=window[b]=r;d&&d(a)};f.src=a};mt.G={};
mt.G.xa=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description&&(a=d.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=d.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return a};
mt.G.ka=function(a,d,f,b,e){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+f+'" height="'+b+'"><param name="movie" value="'+d+'" /><param name="flashvars" value="'+(e||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+f+'" height="'+b+'" src="'+d+'" flashvars="'+(e||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.k=function(a,d){var f=a.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return f?f[3]:r};mt.url.Va=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:r};mt.url.ta=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):r};mt.url.T=function(a){return(a=mt.url.ta(a))?a.replace(/:\d+$/,""):a};mt.url.Ua=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):r};
h.p={Ea:"http://tongji.baidu.com/hm-web/welcome/ico",O:"hm.baidu.com/hm.gif",ca:"baidu.com",Ba:"hmmd",Ca:"hmpl",Aa:"hmkw",ya:"hmci",Da:"hmsr",za:"hmcu",q:0,l:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",Xa:0,ha:6E5,ia:10,R:1024,ga:1,z:2147483647,$:"cc cf ci ck cl cm cp cu cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api tt u".split(" ")};
(function(){var a={o:{},c:function(a,f){this.o[a]=this.o[a]||[];this.o[a].push(f)},A:function(a,f){this.o[a]=this.o[a]||[];for(var b=this.o[a].length,e=0;e<b;e++)this.o[a][e](f)}};return h.s=a})();
(function(){function a(a,b){var e=document.createElement("script");e.charset="utf-8";d.e(b,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=r,b()}:e.onload=function(){b()});e.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(e,l)}var d=mt.lang;return h.load=a})();
(function(){var a=h.p,d=mt.G,f={init:function(){if(""!==c.icon){var b;b=c.icon.split("|");var e=a.Ea+"?s="+c.id,f=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+b[0]+"."+b[1];switch(b[1]){case "swf":b=d.ka("HolmesIcon"+a.l,f,b[2],b[3],"s="+e);break;case "gif":b='<a href="'+e+'" target="_blank"><img border="0" src="'+f+'" width="'+b[2]+'" height="'+b[3]+'"></a>';break;default:b='<a href="'+e+'" target="_blank">'+b[0]+"</a>"}document.write(b)}}};h.s.c("pv-b",f.init);return f})();
(function(){var a=mt.r,d=mt.event,f=mt.j,b=h.p,e=[],l={aa:function(){c.ctrk&&(d.c(document,"mouseup",l.fa()),d.c(window,"unload",function(){l.D()}),setInterval(function(){l.D()},b.ha))},fa:function(){return function(a){a=l.qa(a);if(""!==a){var d=(b.protocol+"//"+b.O+"?"+h.b.Z().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;d+(b.z+"").length>b.R||(d+encodeURIComponent(e.join(",")+(e.length?",":"")).length+(b.z+"").length>b.R&&l.D(),e.push(a),(e.length>=b.ia||/t:a/.test(a))&&l.D())}}},
qa:function(e){if(0===b.ga){var d=e.target||e.srcElement,k=d.tagName.toLowerCase();if("embed"==k||"object"==k)return""}f.V?(d=Math.max(document.documentElement.scrollTop,document.body.scrollTop),k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),k=e.clientX+k,d=e.clientY+d):(k=e.pageX,d=e.pageY);var m=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:k-=m/2;break;case 2:k-=m}k="{x:"+k+",y:"+d+",";d=e.target||e.srcElement;
return k=(e="a"==d.tagName.toLowerCase()?d:a.pa(d))?k+("t:a,u:"+encodeURIComponent(e.href)+"}"):k+"t:b}"},D:function(){0!==e.length&&(h.b.a.et=2,h.b.a.ep="["+e.join(",")+"]",h.b.i(),e=[])}};h.s.c("pv-b",l.aa);return l})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.I.va()+","+h.I.sa();h.b.i()}}function d(){clearTimeout(x);var a;w&&(a="visible"==document[w]);y&&(a=!document[y]);g="undefined"==typeof a?q:a;if((!p||!k)&&g&&m)u=q,n=+new Date;else if(p&&k&&(!g||!m))u=s,t+=+new Date-n;p=g;k=m;x=setTimeout(d,100)}function f(a){var n=document,k="";if(a in n)k=a;else for(var b=["webkit","ms","moz","o"],t=0;t<b.length;t++){var e=b[t]+a.charAt(0).toUpperCase()+a.slice(1);if(e in n){k=
e;break}}return k}function b(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))m="focus"==a.type||"focusin"==a.type?q:s,d()}var e=mt.event,l=h.s,p=q,g=q,k=q,m=q,v=+new Date,n=v,t=0,u=q,w=f("visibilityState"),y=f("hidden"),x;d();(function(){var a=w.replace(/[vV]isibilityState/,"visibilitychange");e.c(document,a,d);e.c(window,"pageshow",d);e.c(window,"pagehide",d);"object"==typeof document.onfocusin?(e.c(document,"focusin",b),e.c(document,"focusout",b)):(e.c(window,"focus",b),
e.c(window,"blur",b))})();h.I={va:function(){return+new Date-v},sa:function(){return u?+new Date-n+t:t}};l.c("pv-b",function(){e.c(window,"unload",a())});return h.I})();
(function(){var a=mt.lang,d=h.p,f=h.load,b={Fa:function(b){if((void 0===window._dxt||a.e(window._dxt,"Array"))&&"undefined"!==typeof h.b){var l=h.b.K();f([d.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(l)].join(""),b)}},Qa:function(b){if(a.e(b,"String")||a.e(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.la=b})();
(function(){function a(k){for(var b in k)if({}.hasOwnProperty.call(k,b)){var e=k[b];f.e(e,"Object")||f.e(e,"Array")?a(e):k[b]=String(e)}}function d(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var f=mt.lang,b=mt.m,e=h.p,l=h.s,p=h.la,g={w:[],F:0,X:s,init:function(){g.d=0;l.c("pv-b",function(){g.ma();g.na()});l.c("pv-d",g.oa);l.c("stag-b",function(){h.b.a.api=g.d||g.F?g.d+"_"+g.F:""});l.c("stag-d",function(){h.b.a.api=0;g.d=0;g.F=0})},ma:function(){var a=window._hmt||
[];if(!a||f.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,k=0;k<arguments.length;k++){var n=arguments[k];f.e(n,"Array")&&(a.cmd[a.id].push(n),"_setAccount"===n[0]&&(1<n.length&&/^[0-9a-f]{32}$/.test(n[1]))&&(n=n[1],a.id=n,a.cmd[n]=a.cmd[n]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},na:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],e=/^_track(Event|MobConv|Order|RTEvent)$/,n=0,t=b.length;n<t;n++){var d=b[n];
e.test(d[0])?g.w.push(d):g.N(d)}a.cmd[c.id]={push:g.N}},oa:function(){if(0<g.w.length)for(var a=0,b=g.w.length;a<b;a++)g.N(g.w[a]);g.w=r},N:function(a){var b=a[0];if(g.hasOwnProperty(b)&&f.e(g[b],"Function"))g[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(g.d|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],s===a||q===a))g.d|=2,h.b.U=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){g.d|=4;h.b.a.et=0;h.b.a.ep="";h.b.L?(h.b.a.nv=0,h.b.a.st=
4):h.b.L=q;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=e.protocol+"//"+document.location.host+a[1];g.X||(h.b.a.su=document.location.href);h.b.i();h.b.a.u=b;h.b.a.su=d}},_trackEvent:function(a){2<a.length&&(g.d|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=d(a[1])+"*"+d(a[2])+(a[3]?"*"+d(a[3]):"")+(a[4]?"*"+d(a[4]):""),h.b.i())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],e=a[4]||3;if(0<b&&6>b&&0<e&&4>e){g.F++;for(var n=(h.b.a.cv||"*").split("!"),t=n.length;t<b-1;t++)n.push("*");n[b-1]=e+"*"+d(a[2])+
"*"+d(a[3]);h.b.a.cv=n.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.Ja("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?e.protocol+"//"+window.location.host+a[1]:a[1],g.X=q)},_trackOrder:function(e){e=e[1];f.e(e,"Object")&&(a(e),g.d|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=b.stringify(e),h.b.i())},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])g.d|=32,h.b.a.et=93,h.b.a.ep=a,h.b.i()},_trackRTPageview:function(e){e=e[1];f.e(e,"Object")&&(a(e),e=b.stringify(e),512>=encodeURIComponent(e).length&&(g.d|=64,h.b.a.rt=e))},_trackRTEvent:function(d){d=d[1];if(f.e(d,"Object")){a(d);d=encodeURIComponent(b.stringify(d));var m=function(a){var n=h.b.a.rt;g.d|=128;h.b.a.et=90;h.b.a.rt=a;h.b.i();h.b.a.rt=n},l=d.length;if(900>=l)m.call(this,d);else for(var l=Math.ceil(l/900),n="block|"+Math.round(Math.random()*
e.z).toString(16)+"|"+l+"|",t=[],u=0;u<l;u++)t.push(u),t.push(d.substring(900*u,900*u+900)),m.call(this,n+t.join("|")),t=[]}},_setUserId:function(a){a=a[1];p.Fa();p.Qa(a)}};g.init();h.da=g;return h.da})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=q,this.a={},this.U=q,this.L=s,this.init())}var d=mt.url,f=mt.Q,b=mt.G,e=mt.lang,l=mt.cookie,p=mt.j,g=mt.localStorage,k=mt.sessionStorage,m=h.p,v=h.s;a.prototype={M:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var e=a.indexOf(b);return-1<e&&e+b.length===a.length},Y:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},B:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.Y(a,c.dm[b]))return q}else{var e=d.T(a);if(e&&this.M(e,c.dm[b]))return q}return s},K:function(){for(var a=document.location.hostname,b=0,e=c.dm.length;b<e;b++)if(this.M(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},S:function(){for(var a=0,b=c.dm.length;a<b;a++){var e=c.dm[a];if(-1<e.indexOf("/")&&this.Y(document.location.href,e))return e.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},wa:function(){if(!document.referrer)return m.l-m.q>c.vdur?1:4;var a=
s;this.B(document.referrer)&&this.B(document.location.href)?a=q:(a=d.T(document.referrer),a=this.M(a||"",document.location.hostname));return a?m.l-m.q>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||k.get(a)||g.get(a)}catch(b){}},setData:function(a,b,e){try{l.set(a,b,{domain:this.K(),path:this.S(),J:e}),e?g.set(a,b,e):k.set(a,b)}catch(d){}},Ja:function(a){try{l.set(a,"",{domain:this.K(),path:this.S(),J:-1}),k.remove(a),g.remove(a)}catch(b){}},Oa:function(){var a,b,e,d,f;m.q=this.getData("Hm_lpvt_"+
c.id)||0;13===m.q.length&&(m.q=Math.round(m.q/1E3));b=this.wa();a=4!==b?1:0;if(e=this.getData("Hm_lvt_"+c.id)){d=e.split(",");for(f=d.length-1;0<=f;f--)13===d[f].length&&(d[f]=""+Math.round(d[f]/1E3));for(;2592E3<m.l-d[0];)d.shift();f=4>d.length?2:3;for(1===a&&d.push(m.l);4<d.length;)d.shift();e=d.join(",");d=d[d.length-1]}else e=m.l,d="",f=1;this.setData("Hm_lvt_"+c.id,e,c.age);this.setData("Hm_lpvt_"+c.id,m.l);e=m.l===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.B(document.location.href)&&
(""===document.referrer||this.B(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=e;this.a.lt=d;this.a.lv=f},Z:function(){for(var a=[],b=0,e=m.$.length;b<e;b++){var d=m.$[b],f=this.a[d];"undefined"!==typeof f&&""!==f&&a.push(d+"="+encodeURIComponent(f))}b=this.a.et;this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},Pa:function(){this.Oa();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=p.Ka;this.a.cl=p.colorDepth+"-bit";
this.a.ln=p.language;this.a.ja=p.javaEnabled?1:0;this.a.ck=p.cookieEnabled?1:0;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=b.xa();this.a.v="1.1.11";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");1===this.a.nv&&(this.a.tt=document.title||"");var a=document.location.href;this.a.cm=d.k(a,m.Ba)||"";this.a.cp=d.k(a,m.Ca)||"";this.a.cw=d.k(a,m.Aa)||"";this.a.ci=d.k(a,m.ya)||"";this.a.cf=d.k(a,m.Da)||"";this.a.cu=d.k(a,m.za)||""},init:function(){try{this.Pa(),0===this.a.nv?this.Ma():
this.P(".*"),h.b=this,this.ea(),v.A("pv-b"),this.La()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(m.protocol+"//"+m.O+"?"+b.join("&"))}},La:function(){function a(){v.A("pv-d")}this.U?(this.L=q,this.a.et=0,this.a.ep="",this.i(a)):a()},i:function(a){var b=this;b.a.rnd=Math.round(Math.random()*m.z);v.A("stag-b");var d=m.protocol+"//"+m.O+"?"+b.Z();v.A("stag-d");b.ba(d);
f.log(d,function(d){b.P(d);e.e(a,"Function")&&a.call(b)})},ea:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),e=-1<document.referrer.indexOf(m.ca),f=d.k(a,"jn"),g=/^heatlink$|^select$/.test(f);a&&(b.test(a)&&e&&g)&&(this.a.rnd=Math.round(Math.random()*m.z),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",m.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,
f))},ba:function(a){var b=k.get("Hm_unsent_"+c.id)||"",e=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+e)+(b?","+b:"");k.set("Hm_unsent_"+c.id,b)},P:function(a){var b=k.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?k.set("Hm_unsent_"+c.id,b):k.remove("Hm_unsent_"+c.id))},Ma:function(){var a=this,
b=k.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),e=function(b){f.log(m.protocol+"//"+decodeURIComponent(b),function(b){a.P(b)})},d=0,g=b.length;d<g;d++)e(b[d])}};return new a})();
(function(){var a=mt.r,d=mt.event,f=mt.url,b=mt.m;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var e=+new Date,l=function(a){var b=performance.timing,e=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:e,end:a,value:0<a-e?a-e:0}},p=r;a.Ia(function(){p=+new Date});var g=function(){var a,d,g;g=l("navigation");d=l("request");g={netAll:d.start-g.start,netDns:l("domainLookup").value,netTcp:l("connect").value,srv:l("response").start-d.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:l("loadEvent").end-g.start};a=document.referrer;var k=a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[],u=r;d=r;if("www.baidu.com"===k[2]||"m.baidu.com"===k[2])u=f.k(a,"qid"),d=f.k(a,"click_t");a=u;g.qid=a!=r?a:"";d!=r?(g.bdDom=p?p-d:0,g.bdRun=e-d,g.bdDef=l("navigation").start-d):(g.bdDom=0,g.bdRun=0,g.bdDef=0);h.b.a.et=87;h.b.a.ep=b.stringify(g);h.b.i()};d.c(window,"load",function(){setTimeout(g,500)})}}catch(k){}})();
(function(){var a=h.p,d={init:function(){try{if("http:"===a.protocol){var b=document.createElement("IFRAME");b.setAttribute("src","http://boscdn.bpc.baidu.com/v1/holmes-moplus/mp-cdn.html");b.style.display="none";b.style.width="1";b.style.height="1";b.Sa="0";document.body.appendChild(b)}}catch(e){}}},f=navigator.userAgent.toLowerCase();-1<f.indexOf("android")&&-1===f.indexOf("micromessenger")&&d.init()})();
(function(){var a=mt.lang,d=mt.event,f=mt.m;if(c.comm&&"undefined"!==typeof h.b){var b=function(a){if(a.item){for(var b=a.length,e=Array(b);b--;)e[b]=a[b];return e}return[].slice.call(a)},e=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,l={click:function(){for(var a=[],d=b(document.getElementsByTagName("a")),d=[].concat.apply(d,b(document.getElementsByTagName("area"))),d=[].concat.apply(d,b(document.getElementsByTagName("img"))),f=0,g=d.length;f<g;f++){var k=d[f],
l=k.getAttribute("onclick"),k=k.getAttribute("href");(e.test(l)||e.test(k))&&a.push(d[f])}return a}},p=function(a,b){for(var e in a)if(a.hasOwnProperty(e)&&b.call(a,e,a[e])===s)return s},g=function(b,d){var g={n:"swt",t:"clk"};g.v=b;if(d){var k=d.getAttribute("href"),l=d.getAttribute("onclick")?""+d.getAttribute("onclick"):r,m=d.getAttribute("id")||"";e.test(k)?(g.sn="mediate",g.snv=k):a.e(l,"String")&&e.test(l)&&(g.sn="wrap",g.snv=l);g.id=m}h.b.a.et=86;h.b.a.ep=f.stringify(g);h.b.i();for(g=+new Date;500>=
+new Date-g;);},k,m="/zoosnet"+(/\/$/.test("/zoosnet")?"":"/"),v=function(b,e){if(k===e)return g(m+b,e),s;if(a.e(e,"Array")||a.e(e,"NodeList"))for(var d=0,f=e.length;d<f;d++)if(k===e[d])return g(m+b+"/"+(d+1),e[d]),s};d.c(document,"click",function(b){b=b||window.event;k=b.target||b.srcElement;var e={};for(p(l,function(b,d){e[b]=a.e(d,"Function")?d():document.getElementById(d)});k&&k!==document&&p(e,v)!==s;)k=k.parentNode})}})();
(function(){var a=mt.event,d=mt.m;if(c.comm&&"undefined"!==typeof h.b){var f=+new Date,b={n:"anti",sb:0,kb:0,clk:0},e=function(){h.b.a.et=86;h.b.a.ep=d.stringify(b);h.b.i()};a.c(document,"click",function(){b.clk++});a.c(document,"keyup",function(){b.kb=1});a.c(window,"scroll",function(){b.sb++});a.c(window,"unload",function(){b.t=+new Date-f;e()});a.c(window,"load",function(){setTimeout(e,5E3)})}})();
(function(){function a(){this.f=r}var d=mt.Q,f=mt.j;a.prototype={Ga:function(a){if(this.f)this.h(a,0);else if(this.isSupported()){try{this.f=new ActiveXObject("BDEXIE.BDExExtension.1"),this.W=q}catch(b){this.W=s}this.W?this.h(a,0):this.h(a,-1)}else this.h(a,-1)},Ra:function(){this.f&&delete this.f;this.f=r},Na:function(a,b,d){if(this.f&&"SetLocalCache"in this.f)try{void 0===this.f.SetLocalCache(a,b)&&this.h(d,0)}catch(f){this.h(d,-1)}else this.h(d,-1)},ua:function(a,b){if(this.f&&"GetLocalCache"in
this.f)try{this.h(b,this.f.GetLocalCache(a))}catch(d){this.h(b,"")}else this.h(b,"")},ra:function(a){if(this.f&&"GetCryptStr"in this.f)try{this.h(a,this.f.GetCryptStr("strEncryptID1"))}catch(b){this.h(a,"")}else this.h(a,"")},h:function(a,b){"function"===typeof a&&a(b,this)},isSupported:function(){if(window.ActiveXObject||"ActiveXObject"in window)try{return!!new ActiveXObject("BDEXIE.BDExExtension.1")}catch(a){}return s},Ha:function(){var a=this;this.ra(function(b){void 0!==b&&""!==b&&(d.log("//datax.baidu.com/x.gif?dm="+
encodeURIComponent("datax.baidu.com/webadapter/guid")+"&ac="+encodeURIComponent(b)+"&v=hm-webadapter-0.0.1&rnd="+Math.round(2147483647*Math.random())),a.Na("hmKey",+new Date,function(){a.Ra()}))})}};if(f.V&&/^http(s)?:$/.test(document.location.protocol)){var b=new a;b.Ga(function(a){0===a&&b.ua("hmKey",function(a){a=+a;(isNaN(a)||6048E5<+new Date-a)&&b.Ha()})})}})();})();
